# Generated by Django 3.0.10 on 2020-10-28 09:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_connectionrdp_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('sequence', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name': 'Macro',
                'verbose_name_plural': 'Macros',
            },
        ),
    ]
