# Generated by Django 3.0.10 on 2020-10-29 06:33
from __future__ import unicode_literals
from django.db import models, migrations


def load_macros(apps, schema_editor):
    Macro = apps.get_model("backend", "Macro")
    macro_cad = Macro(id=0, name='Ctrl+Alt+Del', sequence='[{"action": "keydown","key": 65507},{"action": "keydown","key": 65513},{"action": "keydown","key": 65535},{"action": "wait","value": 100},{"action": "keyup","key": 65535},{"action": "keyup","key": 65507},{"action": "keyup","key": 65513}]')
    macro_cad.save()
    macro_af4 = Macro(id=1, name='Alt+F4', sequence='[{"action": "keydown","key": 65513},{"action": "keydown","key": 65473},{"action": "wait","value": 100},{"action": "keyup","key": 65473},{"action": "keyup","key": 65513}]')
    macro_af4.save()


def delete_macros(apps, schema_editor):
    Macro = apps.get_model("backend", "Macro")
    Macro.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_macros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Macros',
            new_name='Macro',
        ),
        migrations.RunPython(load_macros,delete_macros),
    ]

