# Generated by Django 3.0.10 on 2020-10-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_macros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Macros',
            new_name='Macro',
        ),
    ]
