# Generated by Django 2.2.17 on 2020-11-23 11:28

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20201029_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalnamedcredentials',
            name='passphrase',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Passphrase'),
        ),
        migrations.AlterField(
            model_name='staticcredentials',
            name='passphrase',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Passphrase'),
        ),
    ]
