# Generated by Django 2.2.17 on 2020-11-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20201123_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrdp',
            name='remote_app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionrdp',
            name='remote_app_args',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectionrdp',
            name='remote_app_working_dir',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
