# Generated by Django 2.2.17 on 2020-11-24 01:15

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20201124_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrdp',
            name='gateway_credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Credentials', verbose_name='Gateway Credentials'),
        ),
        migrations.AddField(
            model_name='connectionrdp',
            name='gateway_domain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gateway Domain'),
        ),
        migrations.AddField(
            model_name='connectionrdp',
            name='gateway_hostname',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='connectionrdp',
            name='gateway_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Gateway Password'),
        ),
        migrations.AddField(
            model_name='connectionrdp',
            name='gateway_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectionrdp',
            name='gateway_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gateway Username'),
        ),
    ]
