# Generated by Django 2.2.17 on 2020-11-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20201124_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrdp',
            name='loadbalancer_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
