# This is a way do build and deploy application for QA - using same Dockerfile which is used to build official image
version: '3'
services:
  server: &server
    tty: true
    build:
      context: ./
      args:
        - DOCKER_TAG=QA
    restart: always
    depends_on:
      - db
    volumes:
#       e.g. to mount LDAP config:
#       - /c/Users/username/dockerdata/guacozy/ldap_config.py:/app/guacozy_server/ldap_config.py
#       - /home/username/dockerdata/guacozy/ldap_config.py:/app/guacozy_server/ldap_config.py
#       e.g. to mount OKTA config:
#        - /home/ubuntu/okta_config.py:/app/guacozy_server/okta_config.py
        - /home/ubuntu/saml2_config.py:/app/guacozy_server/saml2_config.py
        - /home/ubuntu/debug/ssl:/ssl
    environment:
      - DJANGO_SECRET_KEY=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz
      - FIELD_ENCRYPTION_KEY=qjq4ObsXMqiqQyfKgD-jjEGm4ep8RaHKGRg4ohGCi1A=
      - DJANGO_DB_URL=postgres://postgres:8Yl3NEeNY70aEM1czh4ovLIZF5g1CDMt@db:5432/postgres
      - DJANGO_ALLOWED_HOSTS=*
    ports:
      - 80:80
      - 443:443
  guacd:
    image: guacamole/guacd
    restart: always
  db:
    image: postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8Yl3NEeNY70aEM1czh4ovLIZF5g1CDMt
    volumes:
      - /home/ubuntu/debug/pg-data:/var/lib/postgresql/data

